# Generated by Django 5.0 on 2024-02-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_title_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='network.post'),
        ),
    ]
